//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINT_VALUES
    {
        public POINT_VALUES()
        {
            this.POINTS = new HashSet<POINT>();
        }
    
        public int POINT_VAL_ID { get; set; }
        public Nullable<int> PHILANTHROPY { get; set; }
        public Nullable<int> INTRAMURALS { get; set; }
        public Nullable<int> STUDY_HOURS { get; set; }
        public Nullable<int> OLYMPICS { get; set; }
        public Nullable<int> SIGNATURES { get; set; }
        public Nullable<int> PLEDGE_BOOK { get; set; }
    
        public virtual ICollection<POINT> POINTS { get; set; }
    }
}
