//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAE_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAEDB : DbContext
    {
        public SAEDB()
            : base("name=SAEDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FACT> FACTs { get; set; }
        public DbSet<PLEDGE> PLEDGEs { get; set; }
        public DbSet<PLEDGE_CLASS> PLEDGE_CLASS { get; set; }
        public DbSet<POINT_VALUES> POINT_VALUES { get; set; }
        public DbSet<POINT> POINTS { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
